# IT IS RECOMMENDED YOU DO NOT CHANGE THE IMAGES TO BE DONLOADED.
images:
  # "images.attacher" defines the container images used for the csi attacher
  # container.
  attacher: quay.io/k8scsi/csi-attacher:v1.2.1

  # "images.provisioner" defines the container images used for the csi provisioner
  # container.
  provisioner: quay.io/k8scsi/csi-provisioner:v1.3.1

  # "images.registrar" defines the container images used for the csi registrar
  # container.
  registrar: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0

