{{- if ne .Values.connection.scsiProtocol "None" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ required "Must provide a storage class name." .Values.storageClass.name}}
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: {{ .Values.storageClass.isDefault | quote }}
    "helm.sh/resource-policy": keep
provisioner: {{ .Values.driverName }}
reclaimPolicy: {{ required "Must provide a storage class reclaim policy." .Values.storageClass.reclaimPolicy }}
allowVolumeExpansion: true
{{- end }}