{{- if ne .Values.connection.scsiProtocol "None" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ required "Must provide a storage class name." .Values.storageClass.name}}-xfs
  annotations:
    "helm.sh/resource-policy": keep
provisioner: {{ .Values.driverName }}
reclaimPolicy: {{ required "Must provide a storage class reclaim policy." .Values.storageClass.reclaimPolicy }}
allowVolumeExpansion: true
parameters:
  FsType: xfs
{{- end }}