apiVersion: v1
kind: Secret
metadata:
  name: powerstore-creds
  # Set driver namespace
  namespace: csi-powerstore
type: Opaque
data:
  # set username to the base64 encoded username
  username:
  # set password to the base64 encoded password
  password:
  # set CHAP secret to the base64 encoded password
  # do this if you've enabled CHAP in myvalues.yaml, minimum 12 symbols
  # chapsecret:
  # set CHAP username to the base64 encoded username
  # chapuser:

